version: "3.9"

services:
  order-service:
    build: .
    ports:
      - "3002:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: saravanan
      DB_PASSWORD: admin
      DB_NAME: order_db

  db:
    image: postgres:18
    container_name: order-db-container
    environment:
      POSTGRES_USER: saravanan
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: order_db
    ports:
      - "5433:5432"
    volumes:
      - order-service_postgres_data_order:/var/lib/postgresql

volumes:
  postgres_data_order:
    name: order-service_postgres_data_order
