networks:
  kafka-net:
    driver: bridge

services:
  kafka:
    image: apache/kafka:4.1.1
    container_name: kafka
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      # KRaft Identity
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      
      # Networking
      # We use 'localhost' so your host machine apps can connect to it
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      
      # KRaft Controller Settings
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      
      # Storage (The IMPORTANT part)
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      # You must provide a Cluster ID for KRaft
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
      
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_MIN_INSYNC_REPLICAS: 1
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - kafka-net
      
  init-kafka:
    image: apache/kafka:4.1.1
    depends_on:
      - kafka
    networks:
      - kafka-net
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      echo 'Waiting for Kafka to be ready...'

      # Wait until Kafka responds
      until /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092 --list; do
        echo 'Kafka not ready yet... retrying in 2s'
        sleep 2
      done

      echo 'Kafka is ready. Creating topics...'

      /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092 --create --if-not-exists --topic orders --partitions 3 --replication-factor 1

      /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092 --create --if-not-exists --topic inventory --partitions 3 --replication-factor 1

      echo 'Topics created:'
      /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092 --list
      "
  
  inventory-service:
    build: ./inventory-service
    # comment ports when we are trying to scale up consumers
    # ports:
    #   - "3001:3001"
    ports:
      - "3001:3001"

    depends_on:
      inventory-db:
        condition: service_started
      kafka:
        condition: service_started
      init-kafka:
        condition: service_completed_successfully
    networks:
      - kafka-net
    environment:
      DB_HOST: inventory-db
      DB_PORT: 5432
      DB_USER: saravanan
      DB_PASSWORD: admin
      DB_NAME: inventory_db
  
  order-service:
    build: ./order-service
    ports:
      - "3002:3002"
    depends_on:
      - order-db
      - kafka
      - init-kafka
    networks:
      - kafka-net
    environment:
      DB_HOST: order-db
      DB_PORT: 5432
      DB_USER: saravanan
      DB_PASSWORD: admin
      DB_NAME: order_db
      INVENTORY_HOST: "inventory-service"
      INVENTORY_PORT: 3001

  order-db:
    image: postgres:18
    container_name: order-db-container
    networks:
      - kafka-net

    environment:
      POSTGRES_USER: saravanan
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: order_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_order:/var/lib/postgresql

  inventory-db:
    image: postgres:18
    container_name: inventory-db-container
    networks:
      - kafka-net
    environment:
      POSTGRES_USER: saravanan
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: inventory_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_new:/var/lib/postgresql
    
volumes:
  postgres_data_new:
    name: inventory-service_postgres_data_new
  postgres_data_order:
    name: order-service_postgres_data_order
  kafka_data: